<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="style.css" type="text/css" />
<title>Telmex - Nuestra p&aacute;gina est&aacute; bajo construcci&oacute;n.</title>
</head>
<body>
<div id="main">
	<div id="box_bg">
		
			<div id="box_bot">
			  <div id="content">
					
					<h1>Bienvenidos a</h1>
				  <p class="link">&nbsp;</p>
					<p class="link"><?php echo $SERVER_NAME;?></p>
					<p>&nbsp;</p>
			    <p>Nuestra p&aacute;gina est&aacute; bajo construcci&oacute;n.<br />
Vis&iacute;tanos pronto.
</p>
					</div>
			</div>
	
	</div>
</div>
</body>
</html>
