export const IMAGES = {
  small: [
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes1-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes2-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes3-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes4-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes5-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes6-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img26-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes8-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes9-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes10-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes11-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes12-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img27-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes15-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes16-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes17-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes18-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img1.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img2.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img3-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img4-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img5-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img6-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img7-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img9-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img10-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img11-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img12-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img13-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img14-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img15-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img16-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img17-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img18-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img19-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img20-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img21-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img22-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img23-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img24-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img25-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes7-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes14-Small.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img28-Small.jpg",
  ],
  medium: [
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes1-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes2-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes3-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes4-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes5-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes6-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img26-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes8-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes9-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes10-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes11-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes12-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img27-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes15-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes16-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes17-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes18-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img1.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img2.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img3-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img4-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img5-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img6-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img7-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img9-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img10-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img11-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img12-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img13-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img14-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img15-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img16-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img17-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img18-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img19-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img20-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img21-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img22-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img23-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img24-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img25-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes7-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes14-Medium.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img28-Medium.jpg",
  ],
  large: [
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes1.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes2.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes3.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes4.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes5.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes6.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img26.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes8.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes9.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes10.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes11.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes12.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img27.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes15.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes16.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes17.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes18.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img1.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img2.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img3.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img4.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img5.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img6.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img7.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img9.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img10.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img11.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img12.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img13.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img14.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img15.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img16.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img17.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img18.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img19.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img20.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img21.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img22.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img23.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img24.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img25.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes7.jpg",
    "https://storage.googleapis.com/cecati13/galeria/zonas_comunes14.jpg",
    "https://storage.googleapis.com/cecati13/galeria/img28.jpg",
  ],
  mockAPI: [
    {
      nombre: "",
      imageHigh: "zonas_comunes1.jpeg",
      imageMedium: "zonas_comunes1-Medium.jpg",
      imageSmall: "zonas_comunes1-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes2.jpeg",
      imageMedium: "zonas_comunes2-Medium.jpg",
      imageSmall: "zonas_comunes2-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes3.jpeg",
      imageMedium: "zonas_comunes3-Medium.jpg",
      imageSmall: "zonas_comunes3-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes4.jpeg",
      imageMedium: "zonas_comunes4-Medium.jpg",
      imageSmall: "zonas_comunes4-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes5.jpeg",
      imageMedium: "zonas_comunes5-Medium.jpg",
      imageSmall: "zonas_comunes5-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes6.jpeg",
      imageMedium: "zonas_comunes6-Medium.jpg",
      imageSmall: "zonas_comunes6-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img26.jpg",
      imageMedium: "img26-Medium.jpg",
      imageSmall: "img26-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes8.jpeg",
      imageMedium: "zonas_comunes8-Medium.jpg",
      imageSmall: "zonas_comunes8-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes9.jpeg",
      imageMedium: "zonas_comunes9-Medium.jpg",
      imageSmall: "zonas_comunes9-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes10.jpeg",
      imageMedium: "zonas_comunes10-Medium.jpg",
      imageSmall: "zonas_comunes10-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes11.jpeg",
      imageMedium: "zonas_comunes11-Medium.jpg",
      imageSmall: "zonas_comunes11-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes12.jpeg",
      imageMedium: "zonas_comunes12-Medium.jpg",
      imageSmall: "zonas_comunes12-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img27.jpg",
      imageMedium: "img27-Medium.jpg",
      imageSmall: "img27-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes15.jpeg",
      imageMedium: "zonas_comunes15-Medium.jpg",
      imageSmall: "zonas_comunes15-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes16.jpeg",
      imageMedium: "zonas_comunes16-Medium.jpg",
      imageSmall: "zonas_comunes16-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes17.jpeg",
      imageMedium: "zonas_comunes17-Medium.jpg",
      imageSmall: "zonas_comunes17-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes18.jpg",
      imageMedium: "zonas_comunes18-Medium.jpg",
      imageSmall: "zonas_comunes18-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img1.jpg",
      imageMedium: "img1.jpg",
      imageSmall: "img1.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img2.jpg",
      imageMedium: "img2.jpg",
      imageSmall: "img2.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img3.jpg",
      imageMedium: "img3-Medium.jpg",
      imageSmall: "img3-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img4.jpg",
      imageMedium: "img4-Medium.jpg",
      imageSmall: "img4-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img5.jpg",
      imageMedium: "img5-Medium.jpg",
      imageSmall: "img5-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img6.jpg",
      imageMedium: "img6-Medium.jpg",
      imageSmall: "img6-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img7.jpg",
      imageMedium: "img7-Medium.jpg",
      imageSmall: "img7-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img9.jpg",
      imageMedium: "img9-Medium.jpg",
      imageSmall: "img9-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img10.jpg",
      imageMedium: "img10-Medium.jpg",
      imageSmall: "img10-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img11.jpg",
      imageMedium: "img11-Medium.jpg",
      imageSmall: "img11-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img12.jpg",
      imageMedium: "img12-Medium.jpg",
      imageSmall: "img12-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img13.jpg",
      imageMedium: "img13-Medium.jpg",
      imageSmall: "img13-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img14.jpg",
      imageMedium: "img14-Medium.jpg",
      imageSmall: "img14-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img15.jpg",
      imageMedium: "img15-Medium.jpg",
      imageSmall: "img15-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img16.jpg",
      imageMedium: "img16-Medium.jpg",
      imageSmall: "img16-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img17.jpg",
      imageMedium: "img17-Medium.jpg",
      imageSmall: "img17-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img18.jpg",
      imageMedium: "img18-Medium.jpg",
      imageSmall: "img18-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img19.jpg",
      imageMedium: "img19-Medium.jpg",
      imageSmall: "img19-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img20.jpg",
      imageMedium: "img20-Medium.jpg",
      imageSmall: "img20-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img21.jpg",
      imageMedium: "img21-Medium.jpg",
      imageSmall: "img21-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img22.jpg",
      imageMedium: "img22-Medium.jpg",
      imageSmall: "img22-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img23.jpg",
      imageMedium: "img23-Medium.jpg",
      imageSmall: "img23-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img24.jpg",
      imageMedium: "img24-Medium.jpg",
      imageSmall: "img24-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img25.jpg",
      imageMedium: "img25-Medium.jpg",
      imageSmall: "img25-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes7.jpeg",
      imageMedium: "zonas_comunes7-Medium.jpg",
      imageSmall: "zonas_comunes7-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "zonas_comunes14.jpeg",
      imageMedium: "zonas_comunes14-Medium.jpg",
      imageSmall: "zonas_comunes14-Small.jpg",
      descripcion: "",
    },
    {
      nombre: "",
      imageHigh: "img28.jpg",
      imageMedium: "img28-Medium.jpg",
      imageSmall: "img28-Small.jpg",
      descripcion: "",
    },
  ],
};
